@startuml
class utils.XmlFileReader {
+ Document readXmlFile(String)
}
class subjects.Product {
- Integer id
- {static} int lastId
- String name
- Coordinates coordinates
- ZonedDateTime creationDate
- Long price
- String partNumber
- Integer manufactureCost
- UnitOfMeasure unitOfMeasure
- Person owner
- {static} Set<String> usedPartNumbers
- void checkPartNumber(String)
+ Integer getId()
+ String getName()
+ Coordinates getCoordinates()
+ ZonedDateTime getCreationDate()
+ Long getPrice()
+ String getPartNumber()
+ void setPartNumber(String)
+ Integer getManufactureCost()
+ void setManufactureCost(Integer)
+ UnitOfMeasure getUnitOfMeasure()
+ void setUnitOfMeasure(UnitOfMeasure)
+ void setCreationDate(ZonedDateTime)
+ Person getOwner()
+ void setOwner(Person)
+ void setId(Integer)
+ String toString()
+ int compareTo(Product)
}
class subjects.Coordinates {
- Integer x
- int y
+ Integer getX()
+ void setX(Integer)
+ int getY()
+ void setY(int)
}
class processors.CommandProcessor {
- ProductCollection productCollection
- Scanner scanner
- String fileName
- Map<String,CommandHandler> commandHandlers
+ void run()
- void initializeCommandHandlers()
+ void processCommand(String)
+ void executeScript(String)
- void help(String)
- void info(String)
- void removeProductById(String)
- void removeProductAt(String)
- void printAscending(String)
- void printFieldDescendingUnitOfMeasure(String)
- void filterByPrice(String)
- void sortCollection(String)
- void reorderCollection(String)
- void clearCollection(String)
- void saveCollectionToFile(String)
- void showCollection(String)
- UnitOfMeasure promptUnitOfMeasure()
- Color promptColor(String)
- Person promptPerson()
- Country promptCountry()
- Location promptLocation()
- void addProduct(String)
- void updateProduct(String)
- Product findProductById(int)
- void exit(String)
}
interface processors.CommandProcessor$CommandHandler {
~ void handle(String)
}
enum subjects.enums.Color {
+  GREEN
+  BLUE
+  YELLOW
+  WHITE
+  ORANGE
}
class Main {
+ {static} void main(String[])
}
class utils.ProductToXmlElementConverter {
+ Element createProductElement(Document,Product)
}
class subjects.Person {
- String name
- String passportID
- Color eyeColor
- Color hairColor
- Country nationality
- Location location
+ String getName()
+ String getPassportID()
+ Color getEyeColor()
+ void setEyeColor(Color)
+ Color getHairColor()
+ void setHairColor(Color)
+ Country getNationality()
+ void setNationality(Country)
+ Location getLocation()
+ void setLocation(Location)
}
class utils.ProductFromXmlElementConverter {
+ Product createProductFromElement(Element)
}
class processors.ProductCollection {
- LinkedList<subjects.Product> products
- ZonedDateTime initializationDate
- XmlFileReader xmlFileReader
- XmlFileWriter xmlFileWriter
- ProductFromXmlElementConverter productFromXmlElementConverter
- ProductToXmlElementConverter productToXmlElementConverter
+ void info()
+ void addProduct(Product)
+ void updateProduct(int,Product)
+ void removeProductById(int)
+ void clearCollection()
+ void saveToFile(String)
+ void loadFromFile(String)
+ void sortCollection()
+ void reorderCollection()
+ void removeProductAt(int)
+ void printAscending()
+ void printFieldDescendingUnitOfMeasure()
+ void filterByPrice(long)
+ LinkedList<Product> getProducts()
}
class subjects.Location {
- Long x
- Integer y
- String name
+ Long getX()
+ void setX(Long)
+ Integer getY()
+ void setY(Integer)
+ String getName()
+ void setName(String)
+ String toString()
}
enum subjects.enums.Country {
+  GERMANY
+  CHINA
+  NORTH_KOREA
+  USA
}
class utils.XmlFileWriter {
+ void writeXmlFile(Document,String)
}
enum subjects.enums.UnitOfMeasure {
+  KILOGRAMS
+  GRAMS
+  MILLIGRAMS
- int value
+ int getValue()
}


subjects.Comparable <|.. subjects.Product
processors.CommandProcessor +.. processors.CommandProcessor$CommandHandler
@enduml